spring.application.name=url_shortener

app.baseUrl=http://localhost:8080
app.durationDaysShortLink=7

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.datasource.url=jdbc:h2:mem:url_shortener_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=urlsh
spring.datasource.password=
spring.h2.console.enabled=true

springdoc.api-docs.path=/api-docs
